MESSAGE:
  REQUIRED_MORE_LEVEL: '&cคุณต้องมีเลเวล &4{1}&c อย่างน้อย &4{2} เพื่อ{3}สื่งนี้ได้ &7(เลเวลของคุณคือ {4})' #To fix add {เพื้อคราฟ}
  ## {1} = DISPLAY_NAME, {2} = requiredLevel, {3} = currentLevel
  EARN_XP: "&aคุณได้รับ &2{1} xp &aจากการ &2{2} &7(Current XP: {3}/{4} xp | Current Level: {5})"
  ## {1} = receivedXP, {2} = DISPLAY_NAME, {3} = currentXP, {4} maxXP, {5} currentLevel
  LEVEL_UP: "&7&m----- &6Level Up &7&m-----&r\n
  &7ยินดีด้วย เลเวล &5{1} &7ของคุณได้เพิ่มขึ้น\n
  &7จาก &6{2} &7-> &c{3}\n
  &7&m-------------------"
  ## {1} = DISPLAY_NAME, {2} = oldLevel, {3} = newLevel
  ITEM_DROP: "{1} Drop! &eคุณได้รับ {2} &7จากการ {3} &7(โอกาส &b{5}%&7)"
CONFIG:
  HIGHEST_LEVEL: 100
  MAX_LV:
    CRAFTS:
      X: 0.3
      Y: 2
    PLANTS:
      X: 0.3
      Y: 2
    FISHS:
      X: 0.3
      Y: 2
    HUNTS:
      X: 0.3
      Y: 2
    MINES:
      X: 0.3
      Y: 2